coverage:
  ignore:
    - "/usr"
    - "dependencies/*"
    - "*/UtestPlatform.cpp"
    - "*/signal_slot_queue.c"
      # This file shares the signal_slot.template but doesn't test it

comment:
  layout: "header, diff, tree"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  branches: null
  flags: null
  paths: null
