image: felipelavratti/ubuntu-buildessentials-scons:16.04

stages:
  - build

build:
  stage: build
  script:
    - scons -Q ./qf_demo_tests/build/qf_demo_dev_tests
    - ./qf_demo_tests/build/qf_demo_dev_tests -v -c
    - scons -Q coverage_report
