image: felipelavratti/ubuntu-buildessentials-scons:16.04

stages:
  - build

job1:
  stage: build
  script:
    - cd dependencies && ./setup-cpputest.sh && cd ../
    - scons -Q ./qf_demo_tests/build/qf_demo_dev_test
    - ./qf_demo_tests/build/qf_demo_dev_test -v -c
