image: felipelavratti/ubuntu-buildessentials-scons:16.04

#cache:
#  paths:
#    - coverage/
#    - tests_runner

stages:
  - build
#  - test
#  - deploy

scons:
  stage: build
  script:
    - scons -Q ./qf_demo_tests/build/qf_demo_dev_tests
    - scons -Q coverage_report
    - scons -Q coverage
    - mv ./qf_demo_tests/build/qf_demo_dev_tests ./tests_runner
#
#test:
#  stage: test
#  script:
    - ./tests_runner -v
    - cat coverage_report
#
#pages:
#  stage: deploy
#  script:
  only:
    - master
