dist: trusty
sudo: required
language: cpp

addons:
  apt:
    packages:
    - lcov

script:
  - scons -Q reacto_tests/build/reacto_host_tests
  - ./reacto_tests/build/reacto_host_tests -v

after_success:
  - scons -Q .coverage.info
  - scons -Q .codecov.ignore
  - bash <(curl -s https://codecov.io/bash) "$(< .codecov.ignore)"
branches:
  - master
