---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [README.md, .gitignore]
permalink: /:title
timezone: null
lsi: false
baseurl: "/reacto"
markdown: kramdown

### content configuration ###
title:       "react.o - Reactive Embedded C"
logo:        "/img/reacto-logo.png"
keywords:    "reactive, embedded, C"
description: "A portable framework for developing reactive embedded systems in C."
source_link: "https://github.com/felipe-lavratti/reacto"
favicon:     "img/icon-32.png"
touch_icon:  "img/icon-128.png"
google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  gray:      '#808075'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  blue2:     '#819bc6'
  turquoise: '#0fbfcf'
  gray-blue: '#D0D0DE'

kramdown:
  auto_ids:  false
